=begin
#DocuSign Rooms API - v2

#An API for an integrator to access the features of DocuSign Rooms

OpenAPI spec version: v2
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module DocuSign_Rooms
  class AccessLevel
    
    CONTRIBUTOR = 'Contributor'.freeze
    OFFICE = 'Office'.freeze
    REGION = 'Region'.freeze
    COMPANY = 'Company'.freeze
    ADMIN = 'Admin'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = AccessLevel.constants.select { |c| AccessLevel::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #AccessLevel" if constantValues.empty?
      value
    end
  end
end
