=begin
#DocuSign Rooms API - v2

#An API for an integrator to access the features of DocuSign Rooms

OpenAPI spec version: v2
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module DocuSign_Rooms
  class RolesFilterContextTypes
    
    ALL_ROLES = 'AllRoles'.freeze
    ASSIGNABLE_ROLES_BASED_ON_COMPANY_PERMISSIONS = 'AssignableRolesBasedOnCompanyPermissions'.freeze
    ASSIGNABLE_ROLES_BASED_ON_ALL_PERMISSIONS = 'AssignableRolesBasedOnAllPermissions'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = RolesFilterContextTypes.constants.select { |c| RolesFilterContextTypes::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #RolesFilterContextTypes" if constantValues.empty?
      value
    end
  end
end
