=begin
#DocuSign Rooms API - v2

#An API for an integrator to access the features of DocuSign Rooms

OpenAPI spec version: v2
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module DocuSign_Rooms
  class RoomDocument
    attr_accessor :document_id

    attr_accessor :name

    attr_accessor :owner_id

    attr_accessor :size

    attr_accessor :folder_id

    attr_accessor :created_date

    attr_accessor :is_signed

    attr_accessor :docu_sign_form_id

    attr_accessor :is_archived

    attr_accessor :is_virtual

    attr_accessor :is_dynamic

    attr_accessor :owner

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'document_id' => :'documentId',
        :'name' => :'name',
        :'owner_id' => :'ownerId',
        :'size' => :'size',
        :'folder_id' => :'folderId',
        :'created_date' => :'createdDate',
        :'is_signed' => :'isSigned',
        :'docu_sign_form_id' => :'docuSignFormId',
        :'is_archived' => :'isArchived',
        :'is_virtual' => :'isVirtual',
        :'is_dynamic' => :'isDynamic',
        :'owner' => :'owner'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'document_id' => :'Integer',
        :'name' => :'String',
        :'owner_id' => :'Integer',
        :'size' => :'Integer',
        :'folder_id' => :'Integer',
        :'created_date' => :'DateTime',
        :'is_signed' => :'BOOLEAN',
        :'docu_sign_form_id' => :'String',
        :'is_archived' => :'BOOLEAN',
        :'is_virtual' => :'BOOLEAN',
        :'is_dynamic' => :'BOOLEAN',
        :'owner' => :'RoomDocumentOwner'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'documentId')
        self.document_id = attributes[:'documentId']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'ownerId')
        self.owner_id = attributes[:'ownerId']
      end

      if attributes.has_key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.has_key?(:'folderId')
        self.folder_id = attributes[:'folderId']
      end

      if attributes.has_key?(:'createdDate')
        self.created_date = attributes[:'createdDate']
      end

      if attributes.has_key?(:'isSigned')
        self.is_signed = attributes[:'isSigned']
      end

      if attributes.has_key?(:'docuSignFormId')
        self.docu_sign_form_id = attributes[:'docuSignFormId']
      end

      if attributes.has_key?(:'isArchived')
        self.is_archived = attributes[:'isArchived']
      end

      if attributes.has_key?(:'isVirtual')
        self.is_virtual = attributes[:'isVirtual']
      end

      if attributes.has_key?(:'isDynamic')
        self.is_dynamic = attributes[:'isDynamic']
      end

      if attributes.has_key?(:'owner')
        self.owner = attributes[:'owner']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          document_id == o.document_id &&
          name == o.name &&
          owner_id == o.owner_id &&
          size == o.size &&
          folder_id == o.folder_id &&
          created_date == o.created_date &&
          is_signed == o.is_signed &&
          docu_sign_form_id == o.docu_sign_form_id &&
          is_archived == o.is_archived &&
          is_virtual == o.is_virtual &&
          is_dynamic == o.is_dynamic &&
          owner == o.owner
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [document_id, name, owner_id, size, folder_id, created_date, is_signed, docu_sign_form_id, is_archived, is_virtual, is_dynamic, owner].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = DocuSign_Rooms.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
